---
# Master node specific variables
kubeadm_init_extra_opts: ""
kubernetes_allow_pods_on_master: false
kubernetes_pod_network:
  cni: calico
  cidr: '192.168.0.0/16'

# API Server configuration
kubernetes_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"
kubernetes_apiserver_port: 6443
