FROM ubuntu:latest

WORKDIR /var/www/html

LABEL maintainer="rajib.conf@gmail.com"
LABEL version="1.2"
LABEL description="Dockerfile for Docker gotto Job Website Lab"

RUN apt-get update && \
    apt-get install nginx -y && \
    echo "Nginx installed successfully."

COPY gotto_job/. .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
