# docker-stack.yml (template)
services:
  clean_work:
    image: rajibconf/clean_work:latest
    ports:
      - "80:80"
    networks:
      - clean_work_net_ov
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  clean_work_net_ov:
    driver: overlay
