apiVersion: v1
kind: Service
metadata:
  name: cleanwork
spec:
  type: NodePort
  selector:
    app: cleanwork
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080   # 👈 fix NodePort here
