#cloud-config
hostname: ${hostname}

package_update: true
package_upgrade: true

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - vim
  - openssh-server
  - git
  - wget
  - gpg

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}

# Enable IP forwarding for Kubernetes
bootcmd:
  - echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.conf
  - echo 'net.bridge.bridge-nf-call-ip6tables = 1' >> /etc/sysctl.conf
  - echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf

runcmd:
  # Load br_netfilter module
  - modprobe br_netfilter
  - echo br_netfilter >> /etc/modules-load.d/k8s.conf
  
  # Apply sysctl settings
  - sysctl --system
  
  # Set timezone
  - timedatectl set-timezone Asia/Dhaka
  
  # Enable SSH service
  - systemctl enable ssh
  - systemctl start ssh