services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ~/gitea-data:/data
    ports:
      - "3000:3000"
      - "222:22"
    restart: always